# Generated by Django 4.2.4 on 2023-10-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ContactCategory',
        ),
        migrations.AddField(
            model_name='debt',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contact'),
        ),
    ]
