# Generated by Django 4.2.4 on 2023-10-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_debt_alter_contact_category_delete_contactcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
