# Generated by Django 4.2.4 on 2023-10-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_debt_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='category',
            field=models.CharField(choices=[('owed', 'Owed'), ('owing', 'Owing')], default='Owed', max_length=10),
            preserve_default=False,
        ),
    ]
