# Generated by Django 4.2.4 on 2023-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_debt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='category',
            field=models.CharField(choices=[('owed', 'Owed'), ('owing', 'Owing')], max_length=10, null=True),
        ),
    ]
