# Generated by Django 4.2.4 on 2023-08-20 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('buyingPrice', models.IntegerField()),
                ('sellingPrice', models.IntegerField()),
                ('discountPrice', models.IntegerField(blank=True, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('rom', models.IntegerField(blank=True, null=True)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('screenSize', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Protector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('buyingPrice', models.IntegerField(blank=True, null=True)),
                ('sellingPrice', models.IntegerField(blank=True, null=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.phone')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.protectortype')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('buyingPrice', models.IntegerField(blank=True, null=True)),
                ('sellingPrice', models.IntegerField(blank=True, null=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.phone')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.casetype')),
            ],
        ),
    ]
