# Generated by Django 4.2.4 on 2023-08-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_phone_ram_remove_phone_rom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='description',
            new_name='other',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='processor',
        ),
    ]
