# Generated by Django 4.2.4 on 2023-08-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_description_phone_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
