# Generated by Django 4.2.4 on 2023-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_phone_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='protector',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
